name: Release Obsidian Plugin
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23.x' # Match local development environment
    # Get the version number and put it in a variable
    - name: Get Version
      id: version
      run: |
        echo "tag=$(git describe --abbrev=0)" >> "$GITHUB_OUTPUT"
    # Build the plugin
    - name: Build
      id: build
      run: |
        npm install
        npm run build --if-present
    # Package the required files into a zip
    - name: Package
      run: |
        mkdir ${{ github.event.repository.name }}
        cp main.js manifest.json styles.css README.md ${{ github.event.repository.name }}
        zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
    # Create the release and upload assets
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          main.js
          manifest.json
          styles.css
          ${{ github.event.repository.name }}.zip
        draft: false
        prerelease: false
    # TODO: release notes???